// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXiZzJ3EIZLsSUnVF4cSqOvqEQUNOy7nI',
    appId: '1:450976963343:web:a438e4009397a13d1dbc7a',
    messagingSenderId: '450976963343',
    projectId: 'venue-vault-kalvium-community',
    authDomain: 'venue-vault-kalvium-community.firebaseapp.com',
    storageBucket: 'venue-vault-kalvium-community.firebasestorage.app',
    measurementId: 'G-1XR0MTDPBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2JdYO6bCTtfp807GoIFv710uxhtFRwc',
    appId: '1:450976963343:android:daff37b1c5c43bb71dbc7a',
    messagingSenderId: '450976963343',
    projectId: 'venue-vault-kalvium-community',
    storageBucket: 'venue-vault-kalvium-community.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaaAQXCIsm2lQUqvcZPX2ThvtV7trSeSI',
    appId: '1:450976963343:ios:7033b86a00cef20c1dbc7a',
    messagingSenderId: '450976963343',
    projectId: 'venue-vault-kalvium-community',
    storageBucket: 'venue-vault-kalvium-community.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaaAQXCIsm2lQUqvcZPX2ThvtV7trSeSI',
    appId: '1:450976963343:ios:7033b86a00cef20c1dbc7a',
    messagingSenderId: '450976963343',
    projectId: 'venue-vault-kalvium-community',
    storageBucket: 'venue-vault-kalvium-community.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXiZzJ3EIZLsSUnVF4cSqOvqEQUNOy7nI',
    appId: '1:450976963343:web:c499f285c11fb31e1dbc7a',
    messagingSenderId: '450976963343',
    projectId: 'venue-vault-kalvium-community',
    authDomain: 'venue-vault-kalvium-community.firebaseapp.com',
    storageBucket: 'venue-vault-kalvium-community.firebasestorage.app',
    measurementId: 'G-FT2DZ3BS5F',
  );
}
